"""Alembic environment.

Alembic runs synchronously via psycopg (v3) against ``DATABASE_URL_SYNC``. The
async runtime engine in ``db.py`` is intentionally not used here — Alembic's
migration runner expects a sync DBAPI.

Three pgvector hooks are wired into this module:

1. ``ischema_names["vector"] = VECTOR`` — teaches SQLAlchemy's PostgreSQL
   dialect to reflect ``vector`` columns as the ``pgvector.sqlalchemy.VECTOR``
   type, which is required for ``--autogenerate`` to recognize existing vector
   columns when comparing the live schema against ``SQLModel.metadata``.

2. ``render_item`` — rewrites pgvector ``VECTOR`` columns to ``Vector(<dim>)``
   in autogenerated migrations and injects the matching import. Without this,
   autogenerate emits a fully-qualified ``pgvector.sqlalchemy.vector.VECTOR(...)``
   reference but never adds ``import pgvector``, breaking every revision that
   touches a vector column.

3. ``target_metadata = SQLModel.metadata`` — importing ``models`` below
   registers Recipe / Ingredient on this metadata, so
   ``alembic revision --autogenerate`` picks them up.
"""

from __future__ import annotations

from logging.config import fileConfig
from typing import Any, Literal

from alembic import context
from alembic.autogenerate.api import AutogenContext
from pgvector.sqlalchemy import VECTOR
from sqlalchemy import engine_from_config, pool
from sqlalchemy.dialects.postgresql.base import ischema_names
from sqlmodel import SQLModel

from settings import get_settings

# Register pgvector's VECTOR type for SQLAlchemy reflection so autogenerate can
# round-trip ``vector`` columns. Must run before any reflection or autogenerate
# call — keep at module top.
ischema_names["vector"] = VECTOR

# Alembic Config object, providing access to values within the .ini file.
config = context.config

# Inject the sync database URL from Settings so the env vars stay the single
# source of truth (alembic.ini intentionally has sqlalchemy.url blank).
config.set_main_option("sqlalchemy.url", get_settings().database_url_sync)

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Models register themselves on ``SQLModel.metadata`` at import time, so this
# import must come before ``target_metadata`` is captured. ``noqa: F401`` is
# intentional — the import is for its side effect, not for use in this module.
from models import Ingredient, Recipe  # noqa: E402, F401

target_metadata = SQLModel.metadata


def render_item(type_: str, obj: Any, autogen_context: AutogenContext) -> str | Literal[False]:
    """Rewrite pgvector ``VECTOR`` columns to a clean ``Vector(<dim>)`` literal.

    Alembic's default rendering for unknown types emits the fully qualified
    module path (``pgvector.sqlalchemy.vector.VECTOR(...)``) without adding the
    matching import, which breaks the generated migration on import. Returning
    a string here both replaces the rendered code and registers the import on
    the autogenerate context.
    """
    if type_ == "type" and isinstance(obj, VECTOR):
        autogen_context.imports.add("from pgvector.sqlalchemy import Vector")
        return f"Vector({obj.dim})"
    return False


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    Configures the context with just a URL and not an Engine, emitting SQL to
    the script output instead of executing it.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_item=render_item,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode against a live database."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_item=render_item,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
