- name: Check if /opt/recettesbot directory exists
  stat:
    path: /opt/recettesbot
  register: recettesbot_dir

- name: Teardown existing Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: /opt/recettesbot
    files:
      - docker-compose.yml
    state: absent
  when: recettesbot_dir.stat.exists

- name: Create /opt/recettesbot directory
  become: true
  file:
    path: "/opt/recettesbot"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Sync project files
  ansible.posix.synchronize:
    src: "../../../{{ item }}"
    dest: "/opt/recettesbot/"
  loop:
    - agent.py
    - bot.py
    - db.py
    - embedding.py
    - main.py
    - models.py
    - pdf.py
    - settings.py
    - pyproject.toml
    - uv.lock
    - alembic.ini
    - entrypoint.sh
    - Dockerfile
    - docker-compose.yml
    - .dockerignore
    - migrations
    - .env

- name: Deploy RecettesBot with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/opt/recettesbot"
    files:
      - docker-compose.yml
    build: always
    state: present
