"""create recipe and ingredient tables

Revision ID: 678fa448339a
Revises: 5a9912c4c8ce
Create Date: 2026-04-10 00:04:31.875925

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  — kept for revisions whose autogen output references sqlmodel.sql.sqltypes
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "678fa448339a"
down_revision: str | Sequence[str] | None = "5a9912c4c8ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.Column("steps", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(768), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("servings > 0", name="ck_recipes_servings_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recipes_embedding_hnsw",
        "recipes",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_recipes_telegram_user_id"), "recipes", ["telegram_user_id"], unique=False
    )
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingredients_recipe_id"), "ingredients", ["recipe_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingredients_recipe_id"), table_name="ingredients")
    op.drop_table("ingredients")
    op.drop_index(op.f("ix_recipes_telegram_user_id"), table_name="recipes")
    op.drop_index(
        "ix_recipes_embedding_hnsw",
        table_name="recipes",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("recipes")
    # ### end Alembic commands ###
